services:
  cassandra:
    image: cassandra:latest
    container_name: cassandra_local
    environment:
      - CASSANDRA_CLUSTER_NAME=Test Cluster
      - CASSANDRA_DC=dc1
      - CASSANDRA_RACK=rack1
      - CASSANDRA_LISTENER_IPV4=0.0.0.0
      - CASSANDRA_LISTENER_IPV6="::"
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
    ports:
      - "9042:9042"   # Cassandra Query Language (CQL) port
      - "7000:7000"   # Cassandra internal communication port
      - "7001:7001"   # SSL communication port
      - "7199:7199"   # JMX monitoring port
      - "9160:9160"   # Thrift port (if needed)
    volumes:
      - cassandra_data:/var/lib/cassandra
    networks:
      - cassandra_network
  dynamodb-local:
    command: "-jar DynamoDBLocal.jar -sharedDb -inMemory -port 8000"
    image: amazon/dynamodb-local:latest
    container_name: dynamodb_local
    ports:
      - "8000:8000"
    volumes:
      - ./dynamodb:/data

volumes:
  cassandra_data:
    driver: local

networks:
  cassandra_network:
    driver: bridge
