name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          build-essential \
          libssl-dev \
          libsasl2-dev \
          libffi-dev \
          libclang-dev \
          cmake \
          unzip \
          curl \
          libuv1-dev

    - name: Build Cassandra Driver
      run: |
        git clone https://github.com/datastax/cpp-driver.git \
          && cd cpp-driver \
          && mkdir build && cd build \
          && cmake .. \
          && make \
          && make install \
          && ldconfig

    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
